endpoint: wss://rpc.astar.network
mock-signature-host: true

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
        - providers: 1
          data:
            free: '1000000000000000000000'
  Assets:
    Account:
      -
        -
          - '18446744073709551620' # IBTC
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
        - balance: '10000000000'
      -
        -
          - '18446744073709551621' # INTR
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
        - balance: '500000000000000'
