---
name: Daily XCM tests
on:
  schedule:
    - cron: '5 * * * *' # Run hourly
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  chopsticks_kintsugi_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Launch chopsticks
        run: |
          npx --yes @acala-network/chopsticks@0.9.3 \
            xcm \
            -r scripts/configs/kusama.yml \
            -p scripts/configs/kintsugi.yml \
            -p scripts/configs/statemine.yml \
            -p scripts/configs/karura.yml \
            -p scripts/configs/parallel-heiko.yml \
            -p scripts/configs/bifrost.yml \
            &> log.txt &
          echo "Waiting for log to show chopsticks is ready..."
          tail -f log.txt | grep -q "Connected parachains"
          echo "... detected chopsticks is ready."

      - name: Run Kintsugi tests
        run: |
          yarn install --frozen-lockfile
          npx ts-node scripts/kintsugi-chopsticks-test.ts
      - name: Show error log
        if: failure()
        run: |
          tail -n 100 log.txt
      - name: Report status to Discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: kintsugi-chopsticks-logs
          path: log.txt
          retention-days: 7

  chopsticks_interlay_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Launch chopsticks
        run: |
          npx --yes @acala-network/chopsticks@0.9.3 \
            xcm \
            -r scripts/configs/polkadot.yml \
            -p scripts/configs/interlay.yml \
            -p scripts/configs/statemint.yml \
            -p scripts/configs/hydradx.yml \
            -p scripts/configs/acala.yml \
            -p scripts/configs/parallel.yml \
            -p scripts/configs/bifrost-polkadot.yml \
            &> log.txt &
          echo "Waiting for log to show chopsticks is ready..."
          tail -f log.txt | grep -q "Connected parachains"
          echo "... detected chopsticks is ready."

      - name: Run Interlay tests
        run: |
          yarn install --frozen-lockfile
          npx ts-node scripts/interlay-chopsticks-test.ts

      - name: Show error log
        if: failure()
        run: |
          tail -n 100 log.txt
      - name: Report status to Discord
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: interlay-chopsticks-logs
          path: log.txt
          retention-days: 7
